CUBRID/cubrid-manual

en/admin/config.rst, en/sql/query/cte.rst, en/sql/query/index.rst
http://jira.cubrid.org/browse/CBRD-21286
=> [CBRD-21286] Add CTE manual

en/sql/query/cte.rst
http://jira.cubrid.org/browse/CBRD-21286
=> [CBRD-21286] markups for reserved words

README.md
=> [CBRD-21220] edit markup of README.md

en/sql/query/delete.rst, en/sql/query/select.rst, en/sql/query/update.rst
http://jira.cubrid.org/browse/CBRD-21291
=> [CBRD-21291] limit clause extension

en/admin/admin_utils.rst
Add an extended description for gen_tz utility.
=> [CBRD-21287] author manual (timezone)

en/admin/admin_utils.rst, en/admin/backup.inc, en/admin/config.rst, en/admin/control.rst, en/admin/db_manage.rst, en/admin/troubleshoot.rst, en/csql.rst, en/quick_start.rst, en/sql/i18n.rst
http://jira.cubrid.org/browse/CBRD-21220
fixes markups, small corrections.
=> [CBRD-21220] fixes markups, small corrections

en/admin/systemtap.rst
http://jira.cubrid.org/browse/CBRD-21302
=> [CBRD-21302] fixes systemtap

en/toc.rst
http://jira.cubrid.org/browse/CBRD-21294
=> [CBRD-21294] build number changes

en/admin/config.rst
http://jira.cubrid.org/browse/CBRD-21290
=> [CBRD-21290] fix system parameters

en/admin/admin_utils.rst
http://jira.cubrid.org/browse/CBRD-20563
=> [CBRD-20563] fix typos on admin_utils

en/sql/transaction.rst
http://jira.cubrid.org/browse/CBRD-20593
=> [CBRD-20593] fix bad example of transaction section

en/install.rst
http://jira.cubrid.org/browse/CBRD-21341
=> [CBRD-21341] fix installation section

en/ha.rst
http://jira.cubrid.org/browse/CBRD-20574
=> [CBRD-20574] remove obsoleted ha_mode on section

en/upgrade.rst
http://jira.cubrid.org/browse/CBRD-21293
=> [CBRD-21293] update upgrade section

en/admin/admin_utils.rst, en/csql.rst, en/sql/catalog.rst, en/sql/schema/table_stmt.rst, en/toc.rst
* fix typos of createdb options
* password encryption method
* referential integrity
=> [CBRD-21220] fix misc stuffs

en/admin/admin_utils.rst, en/admin/backup.inc, en/admin/config.rst, en/admin/control.rst, en/admin/migration.inc, en/admin/systemtap.rst, en/admin/troubleshoot.rst, en/release_note/r10_0.rst, en/sql/datatype.rst, en/sql/i18n.rst, en/sql/literal.rst, en/sql/query/delete.rst, en/sql/query/hq.rst, en/sql/query/select.rst, en/sql/query/update.rst, en/sql/schema/serial_stmt.rst, en/sql/schema/table_stmt.rst, en/sql/schema/view_stmt.rst, en/sql/transaction.rst
http://jira.cubrid.org/browse/CBRD-21373
=> [CBRD-21373] fixes misspelled

en/release_note/changes_10_1.rst, en/sql/index.rst, en/upgrade.rst
add new changes: #751, #752, #753, #754, #755, #756
=> add new changes: #751, #752, #753, #754, #755, #756

en/api/node_js.rst
=> fixes bad FIXME

en/install.rst
* fixes typo
* describes to designate $CUBRID_DATASES folder
* warning about 32-bit Windows
=> [CBRD-21447] fixes installation

en/api/cciapi.rst, ko/api/cciapi.rst
=> Update cciapi.rst - Add CCI_PARAM_AUTO_COMMIT

en/admin/control.rst, en/index.rst
=> [CBRD-21447] updates version

en/admin/admin_utils.rst, en/admin/config.rst
http://jira.cubrid.org/browse/CBRD-21458
=> [CBRD-21458] Rephrase explaining database/volume size

en/release_note/changes_10_1.rst
=> [CBRD-21222] add new changes: #761 .. #777

en/sql/function/analysis_fn.rst
Add json_objagg json_arrayagg to aggregate functions' manual
=> [JSON manual] json aggregate functions

en/sql/function/json_fn.rst
=> [JSON manual] json search function

en/admin/admin_utils.rst
http://jira.cubrid.org/browse/CBRD-23494
Add a new section for heap bestspace statistics (two stats moved for heap section).
=> [CBRD-23494] heap bestspace section

en/sql/function/json_fn.rst
Add json_contains and json_contains_path
=> [JSON manual] json contains

en/sql/function/json_fn.rst
Add json_merge, json_merge_preserve & json_merge_patch to manual.
=> [JSON manual] json_merge_preserve & json_merge_patch

en/sql/function/json_fn.rst
Add json_array_append, json_array_insert, json_insert, json_set, json_replace, json_remove to manual.
=> [JSON manual] json inserts

en/admin/admin_utils.rst
http://jira.cubrid.org/browse/CBRD-23494
=> [CBRD-23494] thread statistics

en/admin/admin_utils.rst
http://jira.cubrid.org/browse/CBRD-23494
=> [CBRD-23494] activation flags

en/admin/config.rst
http://jira.cubrid.org/browse/CBRD-23493
=> [CBRD-23493] data_file_os_advise system parameter

en/admin/config.rst
http://jira.cubrid.org/browse/CBRD-23493
this patch concludes new (not hidden) system parameters
=> [CBRD-23493] thread related parameters

en/sql/datatype.rst
Json path & json pointer description.
=> [JSON manual] json path

en/sql/query/cte.rst
http://jira.cubrid.org/browse/CBRD-23495
CTE in DML& CREATE  examples
=> [CBRD-23495] Add CTE for DML & CREATE examples

en/sql/schema/table_stmt.rst
http://jira.cubrid.org/browse/CBRD-23497
Add ON UPDATE manual entry.
=> [CBRD-23497] add ON update

en/admin/backup.inc
http://jira.cubrid.org/browse/CBRD-23564
=> [CBRD-23564][backupdb] remove -e option

en/admin/migration.inc
http://jira.cubrid.org/browse/CBRD-23491
This is a WIP. Please tell me if formatting looks all right and what topics should I focus on if I missed anything. :)
=> [CBRD-23491] Update loaddb manual

en/sql/query/index.rst, en/sql/query/json_table.rst
=> [JSON manual] json table

en/sql/catalog.rst, en/sql/schema/index_stmt.rst
http://jira.cubrid.org/browse/CBRD-23490
Create online index.
=> [CBRD-23490] create online index

en/admin/backup.inc, en/sql/datatype.rst, en/sql/function/typecast_fn.rst
Added intro paragraph for JSON type, how to create JSON data and validation section.
=> [CBRD-23492] JSON data type, creation and validation

en/admin/control.rst, en/csql.rst, en/index.rst, en/install.rst, en/quick_start.rst, en/toc.rst, en/upgrade.rst
http://jira.cubrid.org/browse/CBRD-23499
The fix remains release notes which should be fixed later.
=> [CBRD-23499] upgrade to 10.2

en/install.rst
http://jira.cubrid.org/browse/CBRD-23585
Add curses lib requirement
=> [CBRD-23585] Add curses lib requirement

en/sql/catalog.rst, en/sql/query/show.rst, en/sql/schema/index_stmt.rst
http://jira.cubrid.org/browse/CBRD-23496
Added information about the new invisible index and the `status` column.
=> [CBRD-23496] Invisible index manual

en/install.rst
http://jira.cubrid.org/browse/CBRD-23498
=> [CBRD-23498] update compatibility chapter

ko/sql/query/delete.rst, ko/sql/query/do.rst, ko/sql/query/hq.rst, ko/sql/query/index.rst, ko/sql/query/insert.rst, ko/sql/query/merge.rst, ko/sql/query/prepare.rst, ko/sql/query/replace.rst, ko/sql/query/select.rst, ko/sql/query/set.rst, ko/sql/query/show.rst, ko/sql/query/truncate.rst, ko/sql/query/update.rst
- Add meta tags for html pages 
- Correct COMMENT description and fix show statements
=> [CBRD-21736] modify sql_query in 10.1 korean manual
